myapp/core/views.py
from flask import render_template, request, Blueprint
from myapp.models import MovieList

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    movie_list = MovieList.query.order_by(MovieList.mood.asc()).paginate(page=page, per_page=10)
    return render_template('index.html', movie_list=movie_list)

myapp/movie_list/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import MovieList
from myapp.movie_list.forms import MovieListForm

movie_list = Blueprint('movie_list', __name__)

@movie_list.route('/create', methods=['GET', 'POST'])
@login_required
def create_movie():
    form = MovieListForm()
    if form.validate_on_submit():
        movie = MovieList(title=form.title.data, genre=form.genre.data, mood=form.mood.data, director=form.director.data, release_year=form.release_year.data, user_id=current_user.id)
        db.session.add(movie)
        db.session.commit()
        flash('Movie Created')
        print('Movie was created')
        return redirect(url_for('core.index'))
    return render_template('create_movie.html', form=form)

@movie_list.route('/<int:movie_id>')
@login_required
def movie(movie_id):
    movie = MovieList.query.get_or_404(movie_id) 
    return render_template('movie.html', title=movie.title, date=movie.date, movie=movie)

@movie_list.route('/<int:movie_id>/update',methods=['GET','POST'])
@login_required
def update(movie_id):
    movie = MovieList.query.get_or_404(movie_id)

    if movie.author != current_user:
        abort(403)

    form = MovieListForm()

    if form.validate_on_submit():
        movie.title = form.title.data
        movie.genre = form.genre.data
        movie.mood = form.mood.data
        movie.director = form.director.data
        movie.release_year = form.release_year.data
        db.session.commit()
        flash('Movie Updated')
        return redirect(url_for('movie_list.movie',movie_id=movie.id))

    elif request.method == 'GET':
        form.title.data = movie.title
        form.genre.data = movie.genre
        form.mood.data = movie.mood
        form.director.data = movie.director
        form.release_year.data = movie.release_year

    return render_template('update.html',title='Updating',form=form)

@movie_list.route('/<int:movie_id>/delete',methods=['GET','POST'])
@login_required
def delete_movie(movie_id):

    movie = MovieList.query.get_or_404(movie_id)
    if movie.author != current_user:
        abort(403)

    db.session.delete(movie)
    db.session.commit()
    flash('Movie Deleted')
    return redirect(url_for('core.index'))

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, MovieList
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 

@users.route('/<username>')
def user_list(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    movie_list = MovieList.query.filter_by(author=user).order_by(MovieList.date.desc()).paginate(page=page, per_page=7) 
    return render_template('user_movie_list.html', movie_list=movie_list, user=user)

# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="three columns">
        <h5>Hello, {{current_user.username}}!</h5>
        <h6><a href="{{url_for('users.user_list', username=current_user.username)}}">My Movies</a></h6>
        <h6><a class="navbar-link" href="{{url_for('users.account')}}">Account</a></h6>
        <h6><a class="logout-link" href="{{url_for('users.logout')}}">Log Out</a></h6>
    </div>

    <div class="nine columns">
        <h5>Edit Account Info</h5>
        <form method="POST" action="" enctype="multipart/form-data">
                {{form.hidden_tag()}}
            <div>
                {{form.username.label}}
                {{form.username(class='u-full-width')}}
            </div>
            <div>
                {{form.email.label}}
                {{form.email(class='u-full-width')}}
            </div>
            <div class="submit-btn">
                {{form.submit(class='u-full-width')}}
            </div>
        </form>
    </div>
</div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script> -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,400;0,600;1,400&display=swap"
        rel="stylesheet">
    <title>Movie Moods</title>
    <link rel="stylesheet" href="../static/normalize.css">
    <link rel="stylesheet" href="../static/skeleton.css">
    <link rel="icon" type="image/x-icon" href="../static/favicon.png">
</head>

<body>
    <nav id="navbar" class="u-full-width">
        <div class="nav-home">
            <a class="home-link" href="{{url_for('core.index')}}">
                Movie Moods
            </a>
        </div>
        {% if current_user.is_authenticated %}
        <div class="nav-item">
            <a class="nav-link" href="{{url_for('users.user_list', username=current_user.username)}}">My Account</a>
        </div>
        {% else %}
        <div class="nav-item">
            <a class="nav-link" href="{{url_for('users.login')}}">Sign in</a> /
            <a class="nav-link" href="{{url_for('users.register')}}">Sign up</a>
        </div>
        {% endif %}
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

myapp/templates/create_movie.html
{% extends "base.html" %}
{% block content %}
<h5>Add a Movie</h5>
<form class="movie-info-form" method="POST">
  {{form.hidden_tag()}}
  <div class="row">
    <div class="nine columns">
      {{form.title.label}} {{form.title(class='u-full-width', placeholder="Required")}}
    </div>
    <div class="three columns">
      {{form.release_year.label}} {{form.release_year(class='u-full-width', placeholder="Required format: yyyy")}}
    </div>
  </div>

  <div class="row">
    <div class="seven columns">
      {{form.director.label}} {{form.director(class='u-full-width', placeholder="Required")}}
    </div>
    <div class="five columns">
      {{form.genre.label}} {{form.genre(class='u-full-width', placeholder="Required")}}
    </div>
  </div>

  <div class="row">
    {{form.mood.label}} {{form.mood(class='u-full-width', placeholder="Required")}}
  </div>

  <div class="submit-btn">
    {{form.submit(class="u-full-width")}}
  </div>

</form>
</div>
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}

{% if current_user.is_authenticated %}
<div>
    <div class="u-full-width">
        <div>
            <h4>Movies to Match Your Moods</h4>
                <h6>Dwell on emotions. Find the movie matches what you're in the mood for.</h6>
                <h6 class="add-movie">What is your go-to movie for a mood? Add <a id="add-movie-link" href="{{url_for('movie_list.create_movie')}}"> here</a>.</h6>
        </div>

    </div>
    <table class="u-full-width" id="movies-table">
        <thead class="row">
            <tr>
                <th></th>
                <th>Mood</th>
                <th>Genre</th>
            </tr>
        </thead>
        <tbody class="row">
            {% for list in movie_list.items %}
            <tr>
                <td><a id="td-title" href="{{url_for('movie_list.movie', movie_id=list.id)}}">{{list.title}},
                        {{list.release_year}}</a></td>
                <td>{{list.mood}}</td>
                <td>{{list.genre}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="u-full-width" id="pages">
    <ul class="row" id="page-nums-group">
        {% for page_num in movie_list.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if movie_list.page == page_num %}
        <li class="page-num" id="page-num-active">
            <a class="page-link-active" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-num">
            <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

{% else %}
<div>
    <div class="u-full-width">
        <div>
            <h4>Movie Moods</h4>
                <p>Dwell on emotions, browse movies to match your moods. What are you in the mood for?</p>
        </div>
    </div>
    <table class="u-full-width" id="movies-table">
        <thead class="row">
            <tr>
                <th>Title</th>
                <th>Mood</th>
                <th>Genre</th>
            </tr>
        </thead>
        <tbody class="row">
            {% for list in movie_list.items %}
            <tr>
                <td><a id="td-title" href="{{url_for('movie_list.movie', movie_id=list.id)}}">{{list.title}},
                        {{list.release_year}}</a></td>
                <td>{{list.mood}}</td>
                <td>{{list.genre}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="u-full-width">
    <ul class="row" id="sign-in-up-group">
        <li class="sign-in-up">
            <a class="sign-link" href="{{url_for('users.login')}}">Sign in</a>
        </li> /
        <li class="sign-in-up">
            <a class="sign-link" href="{{url_for('users.register')}}">Sign up</a>
        </li>
        to explore more movies
    </ul>
</div>

{% endif %}
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="three columns">
        <h5>Sign in</h5>
    </div>

    <div class="nine columns">
        <h5>Welcome Back!</h5>
        <form method="POST">
            {{form.hidden_tag()}}
            <div>
                {{form.email.label}}{{form.email(class='u-full-width')}}
            </div>
            <div>
                {{form.password.label}}{{form.password(class='u-full-width')}}
            </div>
            <div class="submit-btn">
                {{form.submit(class='u-full-width')}}
            </div>
        </form>
    </div>
</div>
{% endblock %}

myapp/templates/movie.html
{% extends "base.html" %}
{% block content %}
<div class="u-full-width">
  <h4>{{movie.title}}</h4>
  <p>{{movie.release_year}} | {{movie.genre}}</p>
  <p>Director: {{movie.director}}</p>
  <p>Watch it when you're in the mood for: <br>{{movie.mood}}</p>

  {% if movie.author == current_user %}
  <div>
    <p class="author">You added this movie on {{movie.date.strftime('%B %d, %Y')}} <a id="edit-btn"
        href="{{ url_for('movie_list.update', movie_id=movie.id) }}">Edit</a>
    </p>
    <form action="{{ url_for('movie_list.delete_movie', movie_id=movie.id) }}" method="POST">
      <input id="delete-btn" type="submit" value="Delete">
    </form>
  </div>
  {% else %}
  <p class="date-author">Added by {{movie.author.username}} on {{movie.date.strftime('%B %d, %Y')}}</p>
  {% endif %}
</div>
{% endblock content %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="three columns">
        <h5>Sign up</h5>
    </div>

    <div class="nine columns">
        <h5>Welcome to Movie Moods</h5>
        <form method="POST">
            {{form.hidden_tag()}}
            <div>
                {{form.email.label}}{{form.email(class='u-full-width')}}
            </div>
            <div>
                {{form.username.label}}{{form.username(class='u-full-width')}}
            </div>
            <div>
                {{form.password.label}}{{form.password(class='u-full-width')}}
            </div>
            <div>
                {{form.pass_confirm.label}}{{form.pass_confirm(class='u-full-width')}}
            </div>
            <div class="submit-btn">
                {{form.submit(class='u-full-width')}}
            </div>
        </form>
    </div>
</div>
{% endblock %}

myapp/templates/update.html
{% extends "base.html" %}
{% block content %}
<h5>Edit a Movie</h5>
<form class="movie-info-form" method="POST">
  {{form.hidden_tag()}}
  <div class="row">
    <div class="nine columns">
      {{form.title.label}} {{form.title(class='u-full-width', placeholder="Required")}}
    </div>
    <div class="three columns">
      {{form.release_year.label}} {{form.release_year(class='u-full-width', placeholder="Required format: yyyy")}}
    </div>
  </div>

  <div class="row">
    <div class="seven columns">
      {{form.director.label}} {{form.director(class='u-full-width', placeholder="Required")}}
    </div>
    <div class="five columns">
      {{form.genre.label}} {{form.genre(class='u-full-width', placeholder="Required")}}
    </div>
  </div>

  <div class="row">
    {{form.mood.label}} {{form.mood(class='u-full-width', placeholder="Required")}}
  </div>

  <div class="submit-btn">
    {{form.submit(class="u-full-width")}}
  </div>
</form>
</div>
{% endblock %}

myapp/templates/user_movie_list.html
{% extends "base.html" %}
{% block content %}

<div class="u-full-width">
  <div class="three columns">
    <h5>Hello, {{current_user.username}}!</h5>
    <h6><a href="{{url_for('users.user_list', username=current_user.username)}}">My Movies</a></h6>
    <h6><a class="navbar-link" href="{{url_for('users.account')}}">Account</a></h6>
    <h6><a class="logout-link" href="{{url_for('users.logout')}}">Log Out</a></h6>
  </div>

  <div class="nine columns">
      <h5>My Movies</h5>

    <table class="u-full-width" id="movies-table">
      <thead class="row">
        <tr>
          <th></th>
          <th>Mood</th>
          <th>Genre</th>
        </tr>
      </thead>
      <tbody class="row">
        {% for list in movie_list.items %}
        <tr>
          <td><a id="td-title" href="{{url_for('movie_list.movie', movie_id=list.id)}}">{{list.title}},
              {{list.release_year}}</a></td>
          <td>{{list.mood}}</td>
          <td>{{list.genre}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="u-full-width" id="pages">
      <ul class="row" id="page-nums-group">
        {% for page_num in movie_list.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if movie_list.page == page_num %}
        <li class="page-num" id="page-num-active">
          <a class="page-link-active" href="{{url_for('users.user_list', username=current_user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-num">
          <a class="page-link" href="{{url_for('users.user_list', username=current_user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
      </ul>
    </div>
  </div>
</div>


{% endblock %}